package vogt.prepa.entities;
// Generated 21 sept. 2018 07:21:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Autorisation generated by hbm2java
 */
@Entity
@Table(name="autorisation"
    ,catalog="prepa"
)
public class Autorisation  implements java.io.Serializable {


     private Integer idautorisation;
     private String code;
     private String libelle;
     private Set<PersonneAutorisee> personneAutorisees = new HashSet<PersonneAutorisee>(0);

    public Autorisation() {
    }

    public Autorisation(String code, String libelle, Set<PersonneAutorisee> personneAutorisees) {
       this.code = code;
       this.libelle = libelle;
       this.personneAutorisees = personneAutorisees;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idautorisation", unique=true, nullable=false)
    public Integer getIdautorisation() {
        return this.idautorisation;
    }
    
    public void setIdautorisation(Integer idautorisation) {
        this.idautorisation = idautorisation;
    }

    
    @Column(name="code", length=45)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle")
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="autorisation")
    public Set<PersonneAutorisee> getPersonneAutorisees() {
        return this.personneAutorisees;
    }
    
    public void setPersonneAutorisees(Set<PersonneAutorisee> personneAutorisees) {
        this.personneAutorisees = personneAutorisees;
    }




}


