package vogt.prepa.entities;
// Generated 3 juil. 2018 16:11:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Classe generated by hbm2java
 */
@Entity
@Table(name="classe"
    ,catalog="prepa"
)
public class Classe  implements java.io.Serializable {


     private Integer idclasse;
     private Filiere filiere;
     private NiveauEtude niveauEtude;
     private Set<Cours> courses = new HashSet<Cours>(0);
     private Set<UtilisateurProfilClasse> utilisateurProfilClasses = new HashSet<UtilisateurProfilClasse>(0);
     private Set<Etudiant> etudiants = new HashSet<Etudiant>(0);

    public Classe() {
    }

    public Classe(Filiere filiere, NiveauEtude niveauEtude, Set<Cours> courses, Set<UtilisateurProfilClasse> utilisateurProfilClasses, Set<Etudiant> etudiants) {
       this.filiere = filiere;
       this.niveauEtude = niveauEtude;
       this.courses = courses;
       this.utilisateurProfilClasses = utilisateurProfilClasses;
       this.etudiants = etudiants;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idclasse", unique=true, nullable=false)
    public Integer getIdclasse() {
        return this.idclasse;
    }
    
    public void setIdclasse(Integer idclasse) {
        this.idclasse = idclasse;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idfiliere")
    public Filiere getFiliere() {
        return this.filiere;
    }
    
    public void setFiliere(Filiere filiere) {
        this.filiere = filiere;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idniveau")
    public NiveauEtude getNiveauEtude() {
        return this.niveauEtude;
    }
    
    public void setNiveauEtude(NiveauEtude niveauEtude) {
        this.niveauEtude = niveauEtude;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classe")
    public Set<Cours> getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set<Cours> courses) {
        this.courses = courses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classe")
    public Set<UtilisateurProfilClasse> getUtilisateurProfilClasses() {
        return this.utilisateurProfilClasses;
    }
    
    public void setUtilisateurProfilClasses(Set<UtilisateurProfilClasse> utilisateurProfilClasses) {
        this.utilisateurProfilClasses = utilisateurProfilClasses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classe")
    public Set<Etudiant> getEtudiants() {
        return this.etudiants;
    }
    
    public void setEtudiants(Set<Etudiant> etudiants) {
        this.etudiants = etudiants;
    }




}


