package vogt.prepa.entities;
// Generated 23 mai 2018 16:30:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cours generated by hbm2java
 */
@Entity
@Table(name="cours"
    ,catalog="prepa"
)
public class Cours  implements java.io.Serializable {


     private Integer idcours;
     private Filiere filiere;
     private Matiere matiere;
     private NiveauEtude niveauEtude;
     private Set<CoursEnseignant> coursEnseignants = new HashSet<CoursEnseignant>(0);

    public Cours() {
    }

    public Cours(Filiere filiere, Matiere matiere, NiveauEtude niveauEtude, Set<CoursEnseignant> coursEnseignants) {
       this.filiere = filiere;
       this.matiere = matiere;
       this.niveauEtude = niveauEtude;
       this.coursEnseignants = coursEnseignants;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcours", unique=true, nullable=false)
    public Integer getIdcours() {
        return this.idcours;
    }
    
    public void setIdcours(Integer idcours) {
        this.idcours = idcours;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idfiliere")
    public Filiere getFiliere() {
        return this.filiere;
    }
    
    public void setFiliere(Filiere filiere) {
        this.filiere = filiere;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idmatiere")
    public Matiere getMatiere() {
        return this.matiere;
    }
    
    public void setMatiere(Matiere matiere) {
        this.matiere = matiere;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idniveau_etude")
    public NiveauEtude getNiveauEtude() {
        return this.niveauEtude;
    }
    
    public void setNiveauEtude(NiveauEtude niveauEtude) {
        this.niveauEtude = niveauEtude;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cours")
    public Set<CoursEnseignant> getCoursEnseignants() {
        return this.coursEnseignants;
    }
    
    public void setCoursEnseignants(Set<CoursEnseignant> coursEnseignants) {
        this.coursEnseignants = coursEnseignants;
    }




}


