package vogt.prepa.entities;
// Generated 3 juil. 2018 16:11:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CoursEnseignant generated by hbm2java
 */
@Entity
@Table(name="cours_enseignant"
    ,catalog="prepa"
)
public class CoursEnseignant  implements java.io.Serializable {


     private Integer idcoursEnseignant;
     private Cours cours;
     private Enseignant enseignant;

    public CoursEnseignant() {
    }

    public CoursEnseignant(Cours cours, Enseignant enseignant) {
       this.cours = cours;
       this.enseignant = enseignant;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcours_enseignant", unique=true, nullable=false)
    public Integer getIdcoursEnseignant() {
        return this.idcoursEnseignant;
    }
    
    public void setIdcoursEnseignant(Integer idcoursEnseignant) {
        this.idcoursEnseignant = idcoursEnseignant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcours")
    public Cours getCours() {
        return this.cours;
    }
    
    public void setCours(Cours cours) {
        this.cours = cours;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idenseignant")
    public Enseignant getEnseignant() {
        return this.enseignant;
    }
    
    public void setEnseignant(Enseignant enseignant) {
        this.enseignant = enseignant;
    }




}


