package vogt.prepa.entities;
// Generated 23 mai 2018 16:30:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Enseignant generated by hbm2java
 */
@Entity
@Table(name="enseignant"
    ,catalog="prepa"
)
public class Enseignant  implements java.io.Serializable {


     private Integer idenseignant;
     private Integer idindividu;
     private Set<CoursEnseignant> coursEnseignants = new HashSet<CoursEnseignant>(0);

    public Enseignant() {
    }

    public Enseignant(Integer idindividu, Set<CoursEnseignant> coursEnseignants) {
       this.idindividu = idindividu;
       this.coursEnseignants = coursEnseignants;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idenseignant", unique=true, nullable=false)
    public Integer getIdenseignant() {
        return this.idenseignant;
    }
    
    public void setIdenseignant(Integer idenseignant) {
        this.idenseignant = idenseignant;
    }

    
    @Column(name="idindividu")
    public Integer getIdindividu() {
        return this.idindividu;
    }
    
    public void setIdindividu(Integer idindividu) {
        this.idindividu = idindividu;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="enseignant")
    public Set<CoursEnseignant> getCoursEnseignants() {
        return this.coursEnseignants;
    }
    
    public void setCoursEnseignants(Set<CoursEnseignant> coursEnseignants) {
        this.coursEnseignants = coursEnseignants;
    }




}


