package vogt.prepa.entities;
// Generated 23 mai 2018 16:30:47 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Etudiant generated by hbm2java
 */
@Entity
@Table(name="etudiant"
    ,catalog="prepa"
)
public class Etudiant  implements java.io.Serializable {


     private Integer idetudiant;
     private AnneeScolaire anneeScolaire;
     private Filiere filiere;
     private Individu individu;
     private NiveauEtude niveauEtude;

    public Etudiant() {
    }

    public Etudiant(AnneeScolaire anneeScolaire, Filiere filiere, Individu individu, NiveauEtude niveauEtude) {
       this.anneeScolaire = anneeScolaire;
       this.filiere = filiere;
       this.individu = individu;
       this.niveauEtude = niveauEtude;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idetudiant", unique=true, nullable=false)
    public Integer getIdetudiant() {
        return this.idetudiant;
    }
    
    public void setIdetudiant(Integer idetudiant) {
        this.idetudiant = idetudiant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idannee_scolaire")
    public AnneeScolaire getAnneeScolaire() {
        return this.anneeScolaire;
    }
    
    public void setAnneeScolaire(AnneeScolaire anneeScolaire) {
        this.anneeScolaire = anneeScolaire;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idfiliere")
    public Filiere getFiliere() {
        return this.filiere;
    }
    
    public void setFiliere(Filiere filiere) {
        this.filiere = filiere;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idindividu")
    public Individu getIndividu() {
        return this.individu;
    }
    
    public void setIndividu(Individu individu) {
        this.individu = individu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idniveau_etude")
    public NiveauEtude getNiveauEtude() {
        return this.niveauEtude;
    }
    
    public void setNiveauEtude(NiveauEtude niveauEtude) {
        this.niveauEtude = niveauEtude;
    }




}


