package vogt.prepa.entities;
// Generated 23 mai 2018 16:30:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Filiere generated by hbm2java
 */
@Entity
@Table(name="filiere"
    ,catalog="prepa"
)
public class Filiere  implements java.io.Serializable {


     private Integer idfiliere;
     private String code;
     private String libelle;
     private Set<Etudiant> etudiants = new HashSet<Etudiant>(0);
     private Set<Cours> courses = new HashSet<Cours>(0);
     private Set<UtilisateurProfilFiliere> utilisateurProfilFilieres = new HashSet<UtilisateurProfilFiliere>(0);

    public Filiere() {
    }

    public Filiere(String code, String libelle, Set<Etudiant> etudiants, Set<Cours> courses, Set<UtilisateurProfilFiliere> utilisateurProfilFilieres) {
       this.code = code;
       this.libelle = libelle;
       this.etudiants = etudiants;
       this.courses = courses;
       this.utilisateurProfilFilieres = utilisateurProfilFilieres;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idfiliere", unique=true, nullable=false)
    public Integer getIdfiliere() {
        return this.idfiliere;
    }
    
    public void setIdfiliere(Integer idfiliere) {
        this.idfiliere = idfiliere;
    }

    
    @Column(name="code", length=45)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle")
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="filiere")
    public Set<Etudiant> getEtudiants() {
        return this.etudiants;
    }
    
    public void setEtudiants(Set<Etudiant> etudiants) {
        this.etudiants = etudiants;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="filiere")
    public Set<Cours> getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set<Cours> courses) {
        this.courses = courses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="filiere")
    public Set<UtilisateurProfilFiliere> getUtilisateurProfilFilieres() {
        return this.utilisateurProfilFilieres;
    }
    
    public void setUtilisateurProfilFilieres(Set<UtilisateurProfilFiliere> utilisateurProfilFilieres) {
        this.utilisateurProfilFilieres = utilisateurProfilFilieres;
    }




}


