package vogt.prepa.entities;
// Generated 29 juin 2018 14:01:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Filiere generated by hbm2java
 */
@Entity
@Table(name="filiere"
    ,catalog="prepa"
)
public class Filiere  implements java.io.Serializable {


     private Integer idfiliere;
     private String code;
     private String libelle;
     private Set<Classe> classes = new HashSet<Classe>(0);

    public Filiere() {
    }

    public Filiere(String code, String libelle, Set<Classe> classes) {
       this.code = code;
       this.libelle = libelle;
       this.classes = classes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idfiliere", unique=true, nullable=false)
    public Integer getIdfiliere() {
        return this.idfiliere;
    }
    
    public void setIdfiliere(Integer idfiliere) {
        this.idfiliere = idfiliere;
    }

    
    @Column(name="code", length=45)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle")
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="filiere")
    public Set<Classe> getClasses() {
        return this.classes;
    }
    
    public void setClasses(Set<Classe> classes) {
        this.classes = classes;
    }




}


