package vogt.prepa.entities;
// Generated 23 mai 2018 16:30:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IndividuPhoto generated by hbm2java
 */
@Entity
@Table(name="individu_photo"
    ,catalog="prepa"
)
public class IndividuPhoto  implements java.io.Serializable {


     private Integer idindividuPhoto;
     private byte[] src;
     private String statut;
     private Set<Individu> individus = new HashSet<Individu>(0);

    public IndividuPhoto() {
    }

    public IndividuPhoto(byte[] src, String statut, Set<Individu> individus) {
       this.src = src;
       this.statut = statut;
       this.individus = individus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idindividu_photo", unique=true, nullable=false)
    public Integer getIdindividuPhoto() {
        return this.idindividuPhoto;
    }
    
    public void setIdindividuPhoto(Integer idindividuPhoto) {
        this.idindividuPhoto = idindividuPhoto;
    }

    
    @Column(name="src")
    public byte[] getSrc() {
        return this.src;
    }
    
    public void setSrc(byte[] src) {
        this.src = src;
    }

    
    @Column(name="statut")
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="individuPhoto")
    public Set<Individu> getIndividus() {
        return this.individus;
    }
    
    public void setIndividus(Set<Individu> individus) {
        this.individus = individus;
    }




}


