package vogt.prepa.entities;
// Generated 23 mai 2018 16:30:47 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Individu generated by hbm2java
 */
@Entity
@Table(name="individu"
    ,catalog="prepa"
)
public class Individu  implements java.io.Serializable {


     private Integer idindividu;
     private IndividuPhoto individuPhoto;
     private String noms;
     private String prenoms;
     private Boolean genre;
     private String civilite;
     private Date datenaiss;
     private String lieunaiss;
     private String tel1;
     private String tel2;
     private String email;
     private String residence;
     private String matricule;
     private Set<Etudiant> etudiants = new HashSet<Etudiant>(0);
     private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);
     private Set<Entree> entrees = new HashSet<Entree>(0);
     private Set<Employe> employes = new HashSet<Employe>(0);
     private Set<Visite> visites = new HashSet<Visite>(0);

    public Individu() {
    }

    public Individu(IndividuPhoto individuPhoto, String noms, String prenoms, Boolean genre, String civilite, Date datenaiss, String lieunaiss, String tel1, String tel2, String email, String residence, String matricule, Set<Etudiant> etudiants, Set<Utilisateur> utilisateurs, Set<Entree> entrees, Set<Employe> employes, Set<Visite> visites) {
       this.individuPhoto = individuPhoto;
       this.noms = noms;
       this.prenoms = prenoms;
       this.genre = genre;
       this.civilite = civilite;
       this.datenaiss = datenaiss;
       this.lieunaiss = lieunaiss;
       this.tel1 = tel1;
       this.tel2 = tel2;
       this.email = email;
       this.residence = residence;
       this.matricule = matricule;
       this.etudiants = etudiants;
       this.utilisateurs = utilisateurs;
       this.entrees = entrees;
       this.employes = employes;
       this.visites = visites;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idindividu", unique=true, nullable=false)
    public Integer getIdindividu() {
        return this.idindividu;
    }
    
    public void setIdindividu(Integer idindividu) {
        this.idindividu = idindividu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idindividu_photo")
    public IndividuPhoto getIndividuPhoto() {
        return this.individuPhoto;
    }
    
    public void setIndividuPhoto(IndividuPhoto individuPhoto) {
        this.individuPhoto = individuPhoto;
    }

    
    @Column(name="noms", length=45)
    public String getNoms() {
        return this.noms;
    }
    
    public void setNoms(String noms) {
        this.noms = noms;
    }

    
    @Column(name="prenoms", length=45)
    public String getPrenoms() {
        return this.prenoms;
    }
    
    public void setPrenoms(String prenoms) {
        this.prenoms = prenoms;
    }

    
    @Column(name="genre")
    public Boolean getGenre() {
        return this.genre;
    }
    
    public void setGenre(Boolean genre) {
        this.genre = genre;
    }

    
    @Column(name="civilite", length=45)
    public String getCivilite() {
        return this.civilite;
    }
    
    public void setCivilite(String civilite) {
        this.civilite = civilite;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datenaiss", length=10)
    public Date getDatenaiss() {
        return this.datenaiss;
    }
    
    public void setDatenaiss(Date datenaiss) {
        this.datenaiss = datenaiss;
    }

    
    @Column(name="lieunaiss", length=45)
    public String getLieunaiss() {
        return this.lieunaiss;
    }
    
    public void setLieunaiss(String lieunaiss) {
        this.lieunaiss = lieunaiss;
    }

    
    @Column(name="tel1", length=45)
    public String getTel1() {
        return this.tel1;
    }
    
    public void setTel1(String tel1) {
        this.tel1 = tel1;
    }

    
    @Column(name="tel2", length=45)
    public String getTel2() {
        return this.tel2;
    }
    
    public void setTel2(String tel2) {
        this.tel2 = tel2;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="residence")
    public String getResidence() {
        return this.residence;
    }
    
    public void setResidence(String residence) {
        this.residence = residence;
    }

    
    @Column(name="matricule", length=45)
    public String getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="individu")
    public Set<Etudiant> getEtudiants() {
        return this.etudiants;
    }
    
    public void setEtudiants(Set<Etudiant> etudiants) {
        this.etudiants = etudiants;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="individu")
    public Set<Utilisateur> getUtilisateurs() {
        return this.utilisateurs;
    }
    
    public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
        this.utilisateurs = utilisateurs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="individu")
    public Set<Entree> getEntrees() {
        return this.entrees;
    }
    
    public void setEntrees(Set<Entree> entrees) {
        this.entrees = entrees;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="individu")
    public Set<Employe> getEmployes() {
        return this.employes;
    }
    
    public void setEmployes(Set<Employe> employes) {
        this.employes = employes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="individu")
    public Set<Visite> getVisites() {
        return this.visites;
    }
    
    public void setVisites(Set<Visite> visites) {
        this.visites = visites;
    }




}


