package vogt.prepa.entities;
// Generated 6 juin 2018 13:00:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Matiere generated by hbm2java
 */
@Entity
@Table(name="matiere"
    ,catalog="prepa"
)
public class Matiere  implements java.io.Serializable {


     private Integer idmatiere;
     private String code;
     private String libelle;
     private Set<Cours> courses = new HashSet<Cours>(0);

    public Matiere() {
    }

    public Matiere(String code, String libelle, Set<Cours> courses) {
       this.code = code;
       this.libelle = libelle;
       this.courses = courses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmatiere", unique=true, nullable=false)
    public Integer getIdmatiere() {
        return this.idmatiere;
    }
    
    public void setIdmatiere(Integer idmatiere) {
        this.idmatiere = idmatiere;
    }

    
    @Column(name="code", length=45)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle", length=45)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="matiere")
    public Set<Cours> getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set<Cours> courses) {
        this.courses = courses;
    }




}


