package vogt.prepa.entities;
// Generated 23 mai 2018 16:30:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NiveauEtude generated by hbm2java
 */
@Entity
@Table(name="niveau_etude"
    ,catalog="prepa"
)
public class NiveauEtude  implements java.io.Serializable {


     private Integer idniveauEtude;
     private String code;
     private String libelle;
     private Integer valeur;
     private Set<Cours> courses = new HashSet<Cours>(0);
     private Set<Etudiant> etudiants = new HashSet<Etudiant>(0);

    public NiveauEtude() {
    }

    public NiveauEtude(String code, String libelle, Integer valeur, Set<Cours> courses, Set<Etudiant> etudiants) {
       this.code = code;
       this.libelle = libelle;
       this.valeur = valeur;
       this.courses = courses;
       this.etudiants = etudiants;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idniveau_etude", unique=true, nullable=false)
    public Integer getIdniveauEtude() {
        return this.idniveauEtude;
    }
    
    public void setIdniveauEtude(Integer idniveauEtude) {
        this.idniveauEtude = idniveauEtude;
    }

    
    @Column(name="code", length=45)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle", length=45)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="valeur")
    public Integer getValeur() {
        return this.valeur;
    }
    
    public void setValeur(Integer valeur) {
        this.valeur = valeur;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="niveauEtude")
    public Set<Cours> getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set<Cours> courses) {
        this.courses = courses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="niveauEtude")
    public Set<Etudiant> getEtudiants() {
        return this.etudiants;
    }
    
    public void setEtudiants(Set<Etudiant> etudiants) {
        this.etudiants = etudiants;
    }




}


