package vogt.prepa.entities;
// Generated 2 juil. 2018 10:52:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NiveauEtude generated by hbm2java
 */
@Entity
@Table(name="niveau_etude"
    ,catalog="prepa"
)
public class NiveauEtude  implements java.io.Serializable {


     private Integer idniveauEtude;
     private String code;
     private String libelle;
     private Integer valeur;
     private Set<Classe> classes = new HashSet<Classe>(0);

    public NiveauEtude() {
    }

    public NiveauEtude(String code, String libelle, Integer valeur, Set<Classe> classes) {
       this.code = code;
       this.libelle = libelle;
       this.valeur = valeur;
       this.classes = classes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idniveau_etude", unique=true, nullable=false)
    public Integer getIdniveauEtude() {
        return this.idniveauEtude;
    }
    
    public void setIdniveauEtude(Integer idniveauEtude) {
        this.idniveauEtude = idniveauEtude;
    }

    
    @Column(name="code", length=45)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle", length=45)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="valeur")
    public Integer getValeur() {
        return this.valeur;
    }
    
    public void setValeur(Integer valeur) {
        this.valeur = valeur;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="niveauEtude")
    public Set<Classe> getClasses() {
        return this.classes;
    }
    
    public void setClasses(Set<Classe> classes) {
        this.classes = classes;
    }




}


