package vogt.prepa.entities;
// Generated 28 juin 2018 13:23:20 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PeriodeCreuse generated by hbm2java
 */
@Entity
@Table(name="periode_creuse"
    ,catalog="prepa"
)
public class PeriodeCreuse  implements java.io.Serializable {


     private Integer idperiodeCreuse;
     private String code;
     private String libelle;
     private Date dateDebut;
     private Date dateFin;

    public PeriodeCreuse() {
    }

    public PeriodeCreuse(String code, String libelle, Date dateDebut, Date dateFin) {
       this.code = code;
       this.libelle = libelle;
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idperiode_creuse", unique=true, nullable=false)
    public Integer getIdperiodeCreuse() {
        return this.idperiodeCreuse;
    }
    
    public void setIdperiodeCreuse(Integer idperiodeCreuse) {
        this.idperiodeCreuse = idperiodeCreuse;
    }

    
    @Column(name="code", length=45)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle", length=45)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_debut", length=19)
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_fin", length=19)
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }




}


