package vogt.prepa.entities;
// Generated 28 juin 2018 13:23:20 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UtilisateurProfilClasse generated by hbm2java
 */
@Entity
@Table(name="utilisateur_profil_classe"
    ,catalog="prepa"
)
public class UtilisateurProfilClasse  implements java.io.Serializable {


     private Integer idutilisateurProfilClasse;
     private Classe classe;
     private UtilisateurProfil utilisateurProfil;

    public UtilisateurProfilClasse() {
    }

    public UtilisateurProfilClasse(Classe classe, UtilisateurProfil utilisateurProfil) {
       this.classe = classe;
       this.utilisateurProfil = utilisateurProfil;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idutilisateur_profil_classe", unique=true, nullable=false)
    public Integer getIdutilisateurProfilClasse() {
        return this.idutilisateurProfilClasse;
    }
    
    public void setIdutilisateurProfilClasse(Integer idutilisateurProfilClasse) {
        this.idutilisateurProfilClasse = idutilisateurProfilClasse;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idclasse")
    public Classe getClasse() {
        return this.classe;
    }
    
    public void setClasse(Classe classe) {
        this.classe = classe;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idutilisateur_profil")
    public UtilisateurProfil getUtilisateurProfil() {
        return this.utilisateurProfil;
    }
    
    public void setUtilisateurProfil(UtilisateurProfil utilisateurProfil) {
        this.utilisateurProfil = utilisateurProfil;
    }




}


