package vogt.prepa.entities;
// Generated 21 sept. 2018 07:21:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VisiteCategorie generated by hbm2java
 */
@Entity
@Table(name="visite_categorie"
    ,catalog="prepa"
)
public class VisiteCategorie  implements java.io.Serializable {


     private Integer idvisiteCategorie;
     private String code;
     private String libelle;
     private Set<Visite> visites = new HashSet<Visite>(0);

    public VisiteCategorie() {
    }

    public VisiteCategorie(String code, String libelle, Set<Visite> visites) {
       this.code = code;
       this.libelle = libelle;
       this.visites = visites;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idvisite_categorie", unique=true, nullable=false)
    public Integer getIdvisiteCategorie() {
        return this.idvisiteCategorie;
    }
    
    public void setIdvisiteCategorie(Integer idvisiteCategorie) {
        this.idvisiteCategorie = idvisiteCategorie;
    }

    
    @Column(name="code", length=45)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle")
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="visiteCategorie")
    public Set<Visite> getVisites() {
        return this.visites;
    }
    
    public void setVisites(Set<Visite> visites) {
        this.visites = visites;
    }




}


